---
title: "HW 3-PART A+B+C+D"
author: "Dürdane Karabacak"
date: "30 11 2019"
output: html_document
---
#HW3

```{r setup, include=FALSE}

```
#PART A 


```{r cars}

stringsAsFactors=FALSE
library(tinytex)
library(glmnet)
library(tidyverse)
library(data.table)

epias_dataset<-read.csv("C:/Users/DÜRDANE KARABACAK/Desktop/IE 582 HW/HW 3/Epiaşdata.csv") %>% as.data.table()
colnames(epias_dataset)<-c("Date", "Time", "Electricity_usage")

Pos_type_dates_hours<-as.POSIXct(paste(epias_dataset$Date, epias_dataset$Time), format="%d.%m.%Y %H:%M")

usage<-epias_dataset$Electricity_usage %>% as.character
usage<-gsub(".", "",usage,fixed = TRUE)
usage<-gsub(",", ".",usage,fixed = TRUE) %>%as.numeric

new_epiasdata<-data.table(Date_Hours=Pos_type_dates_hours, Electricity_usage=usage)
str(new_epiasdata)
summary(new_epiasdata)


#PART A 
#Filetering Time Series Data
test_data_Epias<- new_epiasdata %>%
filter(Date_Hours>="2019-11-01")

test_data_Epias$naive48<-new_epiasdata %>%
filter(Date_Hours %in% unique(test_data_Epias$Date_Hours-3600*48)) %>%
  select(Electricity_usage)

test_data_Epias$naive168<-new_epiasdata %>%
filter(Date_Hours %in% unique(test_data_Epias$Date_Hours-3600*168)) %>%
select(Electricity_usage)


test_data_Epias$MAPE_48<-abs(test_data_Epias$naive48-test_data_Epias$Electricity_usage)/test_data_Epias$Electricity_usage
test_data_Epias$MAPE_168<-abs(test_data_Epias$naive168-test_data_Epias$Electricity_usage)/test_data_Epias$Electricity_usage

colnames(test_data_Epias)<-c("Date_and_time", "Electricity_usage", "Naive Forecast-2Days","Naive Forecast_7_Days","MAPE(48)","MAPE(168)")
head(test_data_Epias)



```
 #PART B

```{r}
#PART B
#Forecast for 48 

f48<-new_epiasdata %>%
  filter(Date_Hours<"2019-11-01") %>%
  mutate(Date_Hours=Date_Hours+(3600*48))
colnames(f48)<-c("Date_Hours","Lag_48")

#Forecast for 168

f168<-new_epiasdata %>% filter(Date_Hours<"2019-11-01") %>% mutate(Date_Hours=Date_Hours+(3600*168))
colnames(f168)<-c("Date_Hours","Lag_168")

# Constructing Linear Regression 

LinRegMod<-new_epiasdata%>% left_join(f48,by="Date_Hours") %>%left_join(f168,by="Date_Hours")


#training Linear Regression model

LinRegTrain <- LinRegMod%>%
  filter(Date_Hours<"2019-11-01") %>%
  select('Lag_48','Lag_168',Electricity_usage)

#Test Linear Regression Model

LinRegTest <- LinRegMod %>% filter(Date_Hours>="2019-11-01")

linearregression<-lm(Electricity_usage ~., data=LinRegTrain)




 hist(linearregression$residuals)
 plot(linearregression$residuals)

 
 
 
prediction_lr<-LinRegTest %>%select('Lag_48','Lag_168')

LinRegTest$linear_forecast<-predict(linearregression,prediction_lr)

#MAPE value for Test Linear Regression 

LinRegTest$MAPE<-abs(LinRegTest$linear_forecast-LinRegTest$Electricity_usage)/LinRegTest$Electricity_usage

```


```{r}

```


#PART C



```{r}
#PART C
date<-epias_dataset$Date %>% as.character %>% as.Date(format="%d.%m.%Y")
hours<-epias_dataset$Time%>% 
  as.numeric()-1
new_epiasdata<-data.table(Date=date, Time=hours, Electricity_usage=usage)
f48 <-new_epiasdata %>% filter(Date<"2019-11-01") %>%mutate(Date=Date+2)
f168 <-new_epiasdata %>% filter(Date<"2019-11-01") %>% mutate(Date=Date+7)

# Construction of linear regression model with seasonality

LinRegSeason<-new_epiasdata%>% left_join(f48,by=c("Date","Time")) %>% left_join(f168,by=c("Date","Time"))
colnames(LinRegSeason)<-c("Date", "Time", "Electricity_usage","f48","f168")

LinRegSeason_test <- LinRegSeason%>%filter(Date>="2019-11-01")

LinRegSeason_train <- LinRegSeason%>%filter(Date<"2019-11-01")

lr_set<-vector("list",24)
linear_forecast_set<-vector("list",24)
for(i in 1:24){
  Electricity_usage_trainset_seasonal<-LinRegSeason_train %>% filter(Time==i-1) %>% select('f48','f168',Electricity_usage)
  lr_set[[i]]<-lm(Electricity_usage ~., data=Electricity_usage_trainset_seasonal)
  prediction_lr_seasonal<-LinRegSeason_test %>% filter(Time==i-1) %>% select('f48','f168')
  linear_forecast_set[[i]]<-predict(lr_set[[i]],prediction_lr_seasonal)
}
LinRegSeason_test$forecast_hourly<-unlist(linear_forecast_set)
LinRegSeason_test$MAPE<-abs(LinRegSeason_test$forecast_hourly-LinRegSeason_test$Electricity_usage)/LinRegSeason_test$Electricity_usage


```

```{r}

```
#PART D

```{r }
#PART D
wide_format7<-spread(new_epiasdata,Time,Electricity_usage) %>% mutate(Date=Date+7)
wide_format2<-spread(new_epiasdata,Time,Electricity_usage) %>% mutate(Date=Date+2) %>%left_join(wide_format7,by="Date")
lasso_test_data <- new_epiasdata %>%filter(Date>="2019-11-01")  


training<-vector("list")
Lasso_results<-list()
set.seed(1)

#Gathering predictions for each hour 

for(i in 1:24){
  training[[i]]<-new_epiasdata %>% filter(Time==i-1) %>% filter(Date<"2019-11-01") %>%
    left_join(wide_format2,by="Date") %>%
    na.omit()
  
  Lasso_test<-new_epiasdata %>%
    filter(Time==i-1) %>%
    filter(Date>="2019-11-01") %>%
    left_join(wide_format2,by="Date") %>%
    na.omit()
  
  Lasso_test<-Lasso_test[4:51] %>% as.matrix
  Electricity_usage_lasso<-training[[i]][3]
  forecast_data<-as.matrix (training[[i]][c(4:51)])
  glmm<-cv.glmnet(forecast_data,Electricity_usage_lasso$Electricity_usage,nfolds=10)
  fit<-glmnet(forecast_data,Electricity_usage_lasso$Electricity_usage,lambda = glmm$lambda.min)
  Lasso_results[[i]]<-predict(fit,Lasso_test)
}

lasso_test_data$prediction<-unlist(Lasso_results)
lasso_test_data$MAPE<-abs(lasso_test_data$prediction-lasso_test_data$Electricity_usage)/lasso_test_data$Electricity_usage
hist(lasso_test_data$MAPE,xlab="MAPE", main =  "Histogram of MAPE of Lasso Model")



```
```{r pressure}

```












```{r}

```

