---
title: "IE_582_Group_Project"
author: "Dürdane Karabacak"
date: "06 01 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Preprocessing and  Feature Engineering 

```{r cars}
library(data.table)
library(anytime)
library(dplyr)
library(tidyverse)
library(plyr)
library(glmnet)
library(lars)
library(caTools)
library(caret)

matches<-read.csv("C:/Users/DÜRDANE KARABACAK/Desktop/4.sınıf 1/IE 582 HW/Project/Data/matches.csv")

Dates<- as.Date(anytime(matches$epoch))
Times<-anytime(matches$epoch)
Hours <- format(as.POSIXct(strptime(Times,"%Y-%m-%d %H:%M",tz="")) ,format = "%H:%M")
matches<-cbind(matches,Dates)
matches<-cbind(matches,Hours)
matches<-data.table(matches)
matches<-matches[match_status=="Finished"]
matches[,"goal_difference"]<- (matches$match_hometeam_score-matches$match_awayteam_score)

Mydata <- matches %>% 
  select(match_id,epoch,match_awayteam_id,match_hometeam_id,match_hometeam_score,match_awayteam_score,Dates,Hours,goal_difference)

#Iwill use after 2017-12-01 training because i will need enough data which is before hand to get goals at last games
training<-Mydata[Dates>="2017-12-01"]



#FEATURE 2:Averages of the goals of HOME TEAM of the last 10 matches

sum<-vector()

#For Home team last 10 games goals counting and average

for (y in 1:length(training$match_id)) {
  #hometeam
  sum[y]=0
  team<- training[y,4]
  team<-as.numeric(team)
  time<- training[y,2]
  time<-as.numeric(time)
  dt=Mydata %>% filter( (match_hometeam_id == team | match_awayteam_id == team), epoch<= time  )
  dt<-setDT(dt)[order(epoch),tail(.SD,10)]
  for(j in 1: nrow(dt)){
    if(dt[j,3]==team){
      
      sum[y]=(sum[y]+dt[j,6])
    }
    else sum[y]=sum[y]
    
    if(dt[j,4]==team){
      sum[y]=(sum[y]+dt[j,5])
    }
    else sum[y]=sum[y]
    #print(j )
    #print(sum)
  }
  # print(y)
}
training$last10_homesum<-sum
training$last10_homesum<-as.numeric(training$last10_homesum)
training[,'average_last10_homegoals']<- training$last10_homesum /10




#FEATURE 2: Averages of the goals of AWAY TEAM of the last 10 matches

#For Away team last 10 games goals counting and average

sum_away<-vector()
for (y in 1:length(training$match_id)) {
  sum_away[y]=0
  team<- training[y,3]
  team<-as.numeric(team)
  time<- training[y,2]
  time<-as.numeric(time)
  dt=Mydata %>% filter( (match_hometeam_id == team | match_awayteam_id == team), epoch<= time  )
  dt<-setDT(dt)[order(epoch),tail(.SD,10)]
  for(j in 1: nrow(dt)){
    if(dt[j,3]==team){
      
      sum_away[y]=(sum_away[y]+dt[j,6])
    }
    else sum_away[y]=sum_away[y]
    
    if(dt[j,4]==team){
      sum_away[y]=(sum_away[y]+dt[j,5])
    }
    else sum_away[y]=sum_away[y]
    #print(j )
    #print(sum_away)
  }
  #print(y)
}
training$last10_sum_away<-sum_away
training$last10_sum_away<-as.numeric(training$last10_sum_away)
training[,'average_last10_sum_away']<- training$last10_sum_away /10





#FEATURE 3: Last 3 games average score for home team for just when it is home team 

sumhome_3<-vector()

#For Home team last 10 games goals counting and average

for (y in 1:length(training$match_id)) {
  #hometeam
  sumhome_3[y]=0
  team<- training[y,4]
  team<-as.numeric(team)
  time<- training[y,2]
  time<-as.numeric(time)
  dt=Mydata %>% filter( (match_hometeam_id == team))
  dt<-setDT(dt)[order(epoch),tail(.SD,3)]
  for(j in 1: nrow(dt)){
    if(dt[j,3]==team){
      
      sumhome_3[y]=(sumhome_3[y]+dt[j,6])
    }
    else sumhome_3[y]=sumhome_3[y]
    
    if(dt[j,4]==team){
      sumhome_3[y]=(sumhome_3[y]+dt[j,5])
    }
    else sumhome_3[y]=sumhome_3[y]
    
  }
  
}
training$last3_homesum<-sumhome_3
training$last3_homesum<-as.numeric(training$last3_homesum)
training[,'average_last3_homegoals']<- training$last3_homesum /3




#FEATURE 4: Last 3 games average score for away team for just when it is away team 

sumaway_3<-vector()

#For Home team last 10 games goals counting and average

for (y in 1:length(training$match_id)) {
  #hometeam
  sumaway_3[y]=0
  team<- training[y,4]
  team<-as.numeric(team)
  time<- training[y,2]
  time<-as.numeric(time)
  dt=Mydata %>% filter( (match_awayteam_id== team))
  dt<-setDT(dt)[order(epoch),tail(.SD,3)]
  for(j in 1: nrow(dt)){
    if(dt[j,3]==team){
      
      sumaway_3[y]=(sumaway_3[y]+dt[j,6])
    }
    else sumaway_3[y]=sumaway_3[y]
    
    if(dt[j,4]==team){
      sumaway_3[y]=(sumaway_3[y]+dt[j,5])
    }
    else sumaway_3[y]=sumaway_3[y]
    
  }
 
}
training$last3_awaysum<-sumaway_3
training$last3_awaysum<-as.numeric(training$last3_awaysum)
training[,'average_last3_awaygoals']<- training$last3_awaysum /3

#FEATURE 5 Last games difference value for both home and away team

difference_home<-vector()
difference_away<-vector()

#For Home team last 10 games goals counting and average

for (y in 1:length(training$match_id)) {
  #hometeam
  team<- training[y,4]  
  team<-as.numeric(team)
  dt=Mydata %>% filter( (match_awayteam_id== team) | match_awayteam_id== team)
  dt<-setDT(dt)[order(epoch),tail(.SD,1)]
    if(dt[1,4]==team ){
      
      difference_home[y]=abs(dt$match_hometeam_score-dt$match_awayteam_score)
    }
    if(dt[1,3]==team){
      difference_home[y]=abs(dt$match_hometeam_score-dt$match_awayteam_score)
    }
 
}
training$difference_home<- difference_home
training$difference_home<-as.numeric(training$difference_home)


for (y in 1:length(training$match_id)) {
  team<- training[y,3]  
  team<-as.numeric(team)
  dt=Mydata %>% filter( (match_awayteam_id== team) | match_awayteam_id== team)
  dt<-setDT(dt)[order(epoch),tail(.SD,1)]
  if(dt[1,4]==team ){
    
    difference_away[y]=abs(dt$match_hometeam_score-dt$match_awayteam_score)
  }
  if(dt[1,3]==team){
    difference_away[y]=abs(dt$match_hometeam_score-dt$match_awayteam_score)
  }
 
 
}

training$difference_away<- difference_away
training$difference_away<-as.numeric(training$difference_away)



#Adding Class Info to the data table


training[,"goal_difference"]<- (training$match_hometeam_score-training$match_awayteam_score)
#training[,'Class']<-vector()
for (i in 1:length(training$match_id)) {
  if(training[i,'goal_difference']<0){
    training[i,"Class"]<-0
  }
  else if(training[i,'goal_difference']==0) 
    training[i,"Class"]<-1
  else training[i,"Class"]<-2
}
#training$Class<- as.numeric(training$Class)




```


#Main table construction and Train and Test data tables constructions

```{r}


MainTable<- training %>% select(average_last10_homegoals,average_last10_sum_away,last3_homesum,last3_awaysum,difference_home,difference_away,Class)
MainTable$average_last10_homegoals<-scale(MainTable$average_last10_homegoals)
MainTable$average_last10_sum_away<-scale(MainTable$average_last10_sum_away)
MainTable$last3_homesum<-scale(MainTable$last3_homesum)
MainTable$last3_awaysum<- scale(MainTable$last3_awaysum)
MainTable$difference_away<- scale(MainTable$difference_away)
MainTable$difference_home<- scale(MainTable$difference_home)

set.seed(47)
indices.test<- sample(x=nrow(MainTable),size=500,replace = FALSE)
data.test<-MainTable[indices.test,]
data.training<-MainTable[-indices.test,]
names(data.training)[1]<-"Home Avg Goals"
names(data.training)[2]<-"Away Avg Goals"
names(data.test)[1]<-"Home Avg Goals"
names(data.test)[2]<-"Away Avg Goals"


```


# Decision Tree Fitting 

```{r}


library(rpart)

data.training$Class<-as.factor(data.training$Class)
DT_classifier<- rpart(formula = data.training$Class~., data = data.training[,1:6],control = rpart.control(minbucket =50, cp=0,09))
#Predicting the test set results
info<-data.test[,-7]
predictions_DT<- predict(DT_classifier,newdata = info, type = 'class')
# Making the Confusion Matrix
confusionmatrix<- table(data.test$Class, predictions_DT)
confusionmatrix
plot(DT_classifier)
#text(DT_classifier)

predictions_DT2<- predict(DT_classifier,newdata = info, type = 'prob')


```





```{r pressure, echo=FALSE}

```

